repos:
  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: "pnpm"
        args: [ "run", "lint" ]
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx|json|yaml|yml|md|html|css|scss)$
      - id: type-check
        name: type-check
        entry: "pnpm"
        args: [ "run", "type-check" ]
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx)$
      - id: format
        name: format
        entry: "pnpm"
        args: [ "run", "format" ]
        language: system
        pass_filenames: false
        files: \.(js|ts|tsx|json|yaml|yml|md|html|css|scss)$
